class Config {
    val SHARED_PREF_NAME = "JavasResto"
    val LOGIN_TOKEN_SHARED_PREF = "LOGIN_TOKEN_SHARED_PREF"
    val LOGIN_NAME_SHARED_PREF = "LOGIN_NAME_SHARED_PREF"
    val LOGIN_EMAIL_SHARED_PREF = "LOGIN_EMAIL_SHARED_PREF"
    val LOGIN_PICT_SHARED_PREF = "LOGIN_PICT_SHARED_PREF"


}